import os
os.system("main.py")
os.system("main.py")
os.system("main.py")
os.system("main.py")
os.system("main.py")
os.system("main.py")
os.system("main.py")
os.system("main.py")
os.system("main.py")
os.system("main.py")